name: Sync to Doge Cloud

on:
  push:
    branches:
      - master
  workflow_dispatch: # Enables manual triggering

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install boto3

    - name: Upload to Doge Cloud
      env:
        BUCKET_NAME: s-sh-4319-blog-1258813047
        ENDPOINT: https://cos.ap-shanghai.myqcloud.com
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python sync_to_doge_cloud.py
