name: Sync to Doge Cloud

on:
  push:
    branches:
      - main  # 监控 main 分支的变动

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install tencentcloud-sdk-python

    - name: Sync file to Doge Cloud
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_ENDPOINT: ${{ secrets.COS_ENDPOINT }}
      run: |
        python -c "
        from tencentcloud.common import credential
        from tencentcloud.common.profile import ClientProfile
        from tencentcloud.common.profile.http_profile import HttpProfile
        from tencentcloud.cos.v5 import cos_client

        cred = credential.Credential('${{ env.COS_SECRET_ID }}', '${{ env.COS_SECRET_KEY }}')
        http_profile = HttpProfile(endpoint='${{ env.COS_ENDPOINT }}')
        client_profile = ClientProfile(httpProfile=http_profile)
        client = cos_client.CosClient(cred, '${{ env.COS_REGION }}', client_profile)

        response = client.upload_file(
            Bucket='${{ env.COS_BUCKET }}',
            LocalFilePath='filename.jpg',  # 将 'filename.jpg' 替换为你实际的文件路径
            Key='filename.jpg',
        )
        print(response)
        "
