name: Sync to Multi-Doge Cloud

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install boto3

    - name: Sync to Multi-Doge Cloud
      run: |
        python sync_to_doge_cloud.py
      env:
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_ENDPOINT: ${{ secrets.COS_ENDPOINT }}
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
