name: Sync Files to COS

on:
  push:
    branches:
      - master  # 你希望同步的目标分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sync files to COS
      run: |
        for file in $(find . -type f); do
          echo "Uploading $file to COS..."
          response=$(curl -s -X PUT "${{ secrets.S3_ENDPOINT }}/${{ secrets.S3_BUCKET }}/$(basename $file)" \
            -H "Host: ${{ secrets.S3_BUCKET }}.cos.ap-shanghai.myqcloud.com" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_KEY }}" \
            -T "$file")
          echo "Response for $file: $response"

          # Check if the response contains any errors
          if [[ $response == *"error"* ]]; then
            echo "Error uploading $file: $response"
          else
            echo "$file uploaded successfully."
          fi
        done
      env:
        S3_BUCKET: s-sh-4319-blog-1258813047
        S3_ENDPOINT: https://cos.ap-shanghai.myqcloud.com
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
