name: Sync Files to DogeCloud

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Sync files to DogeCloud
      run: |
        for file in $(find . -type f); do
          echo "Uploading $file to DogeCloud..."

          # Prepare the URL and headers
          bucket="${{ secrets.S3_BUCKET }}"
          key=$(basename "$file")
          url="https://api.dogecloud.com/oss/upload/put.json?bucket=${bucket}&key=${key}"

          # Generate the signature
          signStr="/oss/upload/put.json?bucket=${bucket}&key=${key}\n"
          signature=$(echo -n "$signStr" | openssl dgst -sha1 -hmac "${{ secrets.SECRET_KEY }}" -binary | base64)
          authorization="TOKEN ${{ secrets.ACCESS_KEY }}:${signature}"

          echo "Request URL: $url"
          echo "Authorization Header: $authorization"

          # Make the request
          response=$(curl -s -o response.json -w "%{http_code}" -X POST "$url" \
            -H "Authorization: $authorization" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$file")

          # Output the response
          echo "HTTP Status Code: $response"
          echo "Response body:"
          cat response.json

          # Check if the response contains any errors
          if [[ $response == "200" && $(jq -r '.code' response.json) == "200" ]]; then
            echo "$file uploaded successfully."
          else
            echo "Error uploading $file: $(cat response.json)"
          fi
        done
      env:
        S3_BUCKET: s-sh-4319-blog-1258813047
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
