name: Sync to Doge Cloud

on:
  push:
    branches:
      - master  # 监控 main 分支的变动

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install qcloud-cos

    - name: Sync file to Doge Cloud
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_ENDPOINT: ${{ secrets.COS_ENDPOINT }}
      run: |
        python -c "
        from qcloud_cos import CosConfig, CosS3Client
        config = CosConfig(
            Region='${{ env.COS_REGION }}', 
            SecretId='${{ env.COS_SECRET_ID }}', 
            SecretKey='${{ env.COS_SECRET_KEY }}'
        )
        client = CosS3Client(config)
        response = client.upload_file(
            Bucket='${{ env.COS_BUCKET }}',
            LocalFilePath='filename.jpg',  # 将 'filename.jpg' 替换为你实际的文件路径
            Key='filename.jpg',
            Endpoint='${{ env.COS_ENDPOINT }}'
        )
        print(response)
        "
