name: Sync to DogeCloud

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip
        pip3 install requests

    - name: Upload to DogeCloud
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET_NAME: 'mybucket'
        FILE_PATH: 'path/to/your/file.jpg'
        UPLOAD_KEY: 'uploaded-file.jpg'
      run: |
        python3 <<EOF
import requests
import json
import hmac
from hashlib import sha1

AccessKey = "${ACCESS_KEY}"
SecretKey = "${SECRET_KEY}"
_bucket = "${BUCKET_NAME}"
_key = "${UPLOAD_KEY}"
body = {
    'channel': 'OSS_UPLOAD',
    'scopes': [
        _bucket + ':' + _key
    ]
}
bodyJSON = json.dumps(body)
apiUrl = '/auth/tmp_token.json'
signStr = apiUrl + "\n" + bodyJSON
signedData = hmac.new(SecretKey.encode('utf-8'), signStr.encode('utf-8'), sha1)
sign = signedData.digest().hex()
Authorization = 'TOKEN ' + AccessKey + ':' + sign

response = requests.post('https://api.dogecloud.com' + apiUrl, data=bodyJSON, headers={
    'Authorization': Authorization,
    'Content-Type': 'application/json'
})
res = response.json()

if res['code'] != 200:
    raise Exception('API Error: ' + res['msg'])

# 上传文件到多吉云
s3_endpoint = res['data']['Buckets'][0]['s3Endpoint']
s3_bucket = res['data']['Buckets'][0]['s3Bucket']
credentials = res['data']['Credentials']

import boto3
from botocore.exceptions import NoCredentialsError

session = boto3.Session(
    aws_access_key_id=credentials['AccessKeyId'],
    aws_secret_access_key=credentials['SecretAccessKey'],
    aws_session_token=credentials['SessionToken']
)
s3 = session.client('s3', endpoint_url=s3_endpoint)

try:
    s3.upload_file('${FILE_PATH}', s3_bucket, _key)
    print('File uploaded successfully.')
except FileNotFoundError:
    print('The file was not found.')
except NoCredentialsError:
    print('Credentials not available.')
EOF
