name: Sync to DogeCloud

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests boto3

    - name: Upload all files to DogeCloud
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python3 <<EOF
import requests
import json
import hmac
from hashlib import sha1
import boto3
import os

# 从环境变量获取 AccessKey 和 SecretKey
AccessKey = "${ACCESS_KEY}"
SecretKey = "${SECRET_KEY}"
bucket_name = "s-sh-4319-blog-1258813047"

# 请求临时上传凭证
body = {
    'channel': 'OSS_UPLOAD',
    'scopes': [bucket_name + ':*']
}
body_json = json.dumps(body)
api_url = '/auth/tmp_token.json'
sign_str = api_url + "\n" + body_json
signed_data = hmac.new(SecretKey.encode('utf-8'), sign_str.encode('utf-8'), sha1)
sign = signed_data.digest().hex()
authorization = 'TOKEN ' + AccessKey + ':' + sign

response = requests.post('https://api.dogecloud.com' + api_url, data=body_json, headers={
    'Authorization': authorization,
    'Content-Type': 'application/json'
})
res = response.json()

if res['code'] != 200:
    raise Exception('API Error: ' + res['msg'])

# 上传文件到多吉云
s3_endpoint = res['data']['Buckets'][0]['s3Endpoint']
s3_bucket = res['data']['Buckets'][0]['s3Bucket']
credentials = res['data']['Credentials']

session = boto3.Session(
    aws_access_key_id=credentials['AccessKeyId'],
    aws_secret_access_key=credentials['SecretAccessKey'],
    aws_session_token=credentials['SessionToken']
)
s3 = session.client('s3', endpoint_url=s3_endpoint)

# 遍历并上传所有文件
for root, dirs, files in os.walk('.'):
    for file_name in files:
        file_path = os.path.join(root, file_name)
        upload_key = os.path.relpath(file_path, start='.')  # 保持相对路径

        try:
            s3.upload_file(file_path, s3_bucket, upload_key)
            print(f'Uploaded {file_path} as {upload_key}')
        except Exception as e:
            print(f'Failed to upload {file_path}: {e}')
EOF
