name: Sync Files to COS

on:
  push:
    branches:
      - master  # 你希望同步的目标分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Sync files to COS
      run: |
        for file in $(find . -type f); do
          echo "Uploading $file to COS..."
          
          # Prepare the URL and headers
          url="${{ secrets.S3_ENDPOINT }}/${{ secrets.S3_BUCKET }}/$(basename $file)"
          host="${{ secrets.S3_BUCKET }}.cos.ap-shanghai.myqcloud.com"

          # Generate a signature (replace with actual signature generation code)
          signature=$(echo -n "PUT\n\n\n$(stat -c%s "$file")\n$(basename $file)" | openssl sha1 -hmac "${{ secrets.SECRET_KEY }}" -binary | base64)

          # Make the request
          response=$(curl -s -X PUT "$url" \
            -H "Host: $host" \
            -H "Authorization: COS ${signature}" \
            -H "Content-Type: application/octet-stream" \
            -T "$file")
  
          # Output the response
          echo "Response for $file: $response"
  
          # Check if the response contains any errors
          if [[ $response == *"error"* ]]; then
            echo "Error uploading $file: $response"
          else
            echo "$file uploaded successfully."
          fi
        done
      env:
        S3_BUCKET: s-sh-4319-blog-1258813047
        S3_ENDPOINT: https://cos.ap-shanghai.myqcloud.com
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
