name: Sync COS

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v3

      - name: Sync to COS
        run: |
          pip install cos-cli
          coscli config --secret-id ${{ secrets.COS_SECRET_ID }} --secret-key ${{ secrets.COS_SECRET_KEY }} --bucket ${{ secrets.COS_BUCKET }} --region ap-shanghai
          coscli sync ./koobaiblog/ cos://$COS_BUCKET/koobaiblog/
        env:
          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
