name: Upload to DogeCloud COS

on:
  push:
    branches:
      - master  # 在推送到 main 分支时触发工作流

jobs:
  upload_all_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        pip install cos-python-sdk-v5

    - name: Upload all files to COS
      run: |
        python upload_all_files.py
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_ENDPOINT: ${{ secrets.COS_ENDPOINT }}
