name: Sync Files to DogeCloud

on:
  push:
    branches:
      - master  # 你希望同步的目标分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sync files to DogeCloud
      run: |
        for file in $(find . -type f); do
          curl -X POST "https://api.dogecloud.com/upload" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_KEY }}" \
            -F "file=@$file" \
            -F "key=$(basename $file)"
        done
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
