name: Sync Files to DogeCloud

on:
  push:
    branches:
      - master  # 你希望同步的目标分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sync files to DogeCloud
      run: |
        for file in $(find . -type f); do
          echo "Uploading $file..."
          response=$(curl -s -X POST "https://api.dogecloud.com/upload" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_KEY }}" \
            -F "file=@$file" \
            -F "key=$(basename $file)")
          echo "Response: $response"

          # Check the 'code' field in the JSON response
          code=$(echo $response | jq -r '.code')
          if [ "$code" != "200" ]; then
            echo "Error uploading $file: $(echo $response | jq -r '.msg')"
          else
            echo "$file uploaded successfully."
          fi
        done
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
