name: Sync COS

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v3

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: Configure s3cmd
        run: |
          s3cmd --configure << EOF
          Access key: ${{ secrets.COS_SECRET_ID }}
          Secret key: ${{ secrets.COS_SECRET_KEY }}
          Default Region: ap-shanghai
          Use HTTPS protocol: True
          EOF

      - name: Sync to COS
        run: |
          s3cmd sync ./koobaiblog/ s3://$COS_BUCKET/koobaiblog/
        env:
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
